blank_issues_enabled: false
contact_links:
  - name: Nova
    url: https://discord.gg/EFTCVQe8Gx
    about: If you're having issues with the menu or any mods, join the Discord server! Our kind support team are here to assist you with help whenever.
